---
title: "Local Adaptive Thresholding"
author: "Shota Ochi"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
---

<style type="text/css">

body, td {
   font-size: 15px;
}
code.r{
  font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, cache=FALSE, comment=NA, verbose=TRUE, 
                      fig.width=7, fig.height=7, dev='jpeg',dev.args=list(quality=50)) 
```

<br />

Local adaptive thresholding technique shows a good performance in extracting objects from inhomogeneous background.

I implemented local adaptive thresholding (ThresholdAdaptive).

You can use it as show below.

```{r} 
library(devtools)
install_github("ShotaOchi/imagerExtra")
library(imagerExtra)
layout(matrix(1:4, 2, 2, byrow=TRUE))
plot(papers, main = "Original")
threshold(papers) %>% plot(main = "A Variant of Otsu")
ThresholdAdaptive(papers, 0, range = c(0,1)) %>% plot(main = "Local Adaptive (k=0)")
ThresholdAdaptive(papers, 0.2, range = c(0,1)) %>% plot(main = "Local Adaptive (k=0.2)")
```